from django.urls import path

from products import views

urlpatterns = [
    path("getAllProducts/", views.get_all_products, name="get_all_products"),
    path("getFavProducts/", views.get_favorite_products, name="get_favorite_products"),
    path("getFeaturedProducts/", views.get_featured_products, name="get_featured_products"),
    path("getNewsProducts/", views.get_news_for_products, name="get_news_for_products"),
    path("getProductById/<int:id_product>", views.get_products_by_id, name="get_products_by_id"),
    path("findProductByName/<str:name_product>", views.find_product_by_name, name="find_product_by_name"),
    path("getProductByTypeGame/<int:id_type_game>", views.get_products_by_type_game, name="get_products_by_type_game"),
    path("getProductByTypeConsole/<int:id_console>", views.get_products_by_type_console, name="get_products_by_id"),
    path("filterProduct/", views.filter_product, name="filter_product"),
    path("getProductByRangePrice/", views.get_products_by_range_price, name="get_products_by_range_price"),
    path("priceSuscriptionProduct/<int:id_product>/<int:type_account>", views.price_suscription_product, name="price_suscription_product"),
    path("getCombinationPriceByGame/<int:id_product>", views.get_combination_price_by_game, name="get_combination_price_by_game"),
    path("licenceByProduct/<int:id_product>/<int:id_console>", views.licence_by_product, name="licence_by_product"),
    path("daysForRentail/", views.days_for_rentail, name="daysForRentail"),
    path("confirmSale/", views.confirm_sale, name="confirmSale"),
    path("salesByUser/<int:id_user>", views.sales_by_user, name="salesByUser"),
    path("getLicensces/", views.get_licences, name="get_products_by_id"),
    path("getConsoles/", views.get_consoles, name="get_products_by_id"),
    path("getTypeGames/", views.get_type_games, name="get_type_games"),
    path("getShoppingCar/", views.get_shopping_car, name="get_shopping_car"),
    path("confirmSaleGet/", views.confirm_sale_get, name="confirm_sale_get"),
    path("updateShoppingCar/<int:shooping_car_id>", views.update_shopping_car, name="update_shopping_car"),
    path("pointsByUser/<int:user_id>", views.update_points_by_user, name="update_points_by_user"),
    path("deleteShoppingCar/<int:shooping_car_id>", views.delete_product_shopping_car, name="delete_shopping_car"),
    path("shoppingCar/", views.shopping_car, name="shopping_car"),
    path("typeAccounts/", views.type_accounts, name="type_accounts"),
    path("systemVariables/<str:variable>", views.system_variables, name="system_variables"),
    path("systemVariablesGroup/<str:variable>", views.system_variables_group, name="system_variables_group"),
    path("sendEmail/", views.sendEmail, name="sendEmail"),
    path("manageFile/", views.manageFile, name="manageFile"),
]