"""
Django settings for ecommerceHardcoregamesBack project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8cn@ply1603#h-4o9bvjbuehv186x7=wg0xqm)q6$s#h_*97xi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'users',
    'products',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware'
]

ROOT_URLCONF = 'ecommerceHardcoregamesBack.urls'

# CORS_ALLOWED_ORIGINS = {
#  'http://localhost:4200',
# }

# CORS_ALLOWED_ORIGIN_REGEXES = [
#     'http://localhost:4200',
# ]

CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)

# CORS_ALLOW_HEADERS = (
#     "accept",
#     "authorization",
#     "content-type",
#     "user-agent",
#     "x-csrftoken",
#     "x-requested-with",
# )

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerceHardcoregamesBack.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'hardcoregames',
        'USER': 'postgres',
        'PASSWORD': '#1998jhoan',
        'HOST': 'localhost',
        'DATABASE_PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_URL_FILES = 'static/files/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

#URL_EPAYCO_CONFIRM_SALE = 'https://secure.epayco.co/validation/v1/reference/'
URL_EPAYCO_CONFIRM_SALE = os.getenv("URL_EPAYCO_CONFIRM_SALE")

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#CONFIRMATION_URL = "https://hard-core-games-test.onrender.com/autenticacion/usuario/mis-compras"
CONFIRMATION_URL = os.getenv("CONFIRMATION_URL")
#DECLINED_URL = "https://hard-core-games-test.onrender.com/"
DECLINED_URL = os.getenv("DECLINED_URL")
PENDING_URL = os.getenv("PENDING_URL")
REDIRECTION_URL_BOLD = os.getenv("REDIRECTION_URL_BOLD")
#REDIRECTION_URL_BOLD = "https://stingray-app-x8hb5.ondigitalocean.app/products/confirmSaleBold/"
FROM_EMAIL=os.getenv("FROM_EMAIL")
#FROM_EMAIL='hardcorgamesx@gmail.com'
#FROM_EMAIL="jhoan0498@gmail.com"
PASS_SMTP=os.getenv("PASS_SMTP")

SUBJECT_EMAIL_FOR_TOKEN = "Código para cambio de contraseña HardCoreGames"
SUBJECT_EMAIL_FOR_SALE = "Confirmación de compra en HardCoreGames"
INFO_TEXT = os.getenv("INFO_TEXT")
#INFO_TEXT = "INFO_TEXT"
EMAIL_FOR_TOKEN = "<html>" \
                    "<body>" \
                        "<h2>Solicitud de nueva contraseña HardCoreGames</h2><br>" \
                        "<justify>Está recibiendo este correo electrónico porque se ha solicitado un cambio de contraseña para la cuenta de HardCoreGames. " \
                        "Su codigo de activacion para cambio de contraseña es:</justify> " \
                    "</body>" \
                  "</html>"

#EMAIL_FOR_SALE = '<div style="max-width:560px;background-color:#f5f5f5;border-radius:5px;margin:40px auto;font-family:Open Sans,Helvetica,Arial;font-size:15px;color:#000000"><div class="adM"> </div><div style="font-weight:normal"> <div class="adM"> </div> <div style="text-align:center;font-weight:600;font-size:26px;padding:20px 0;padding-top:41px;padding-bottom:22px"><img src="https://firebasestorage.googleapis.com/v0/b/hardcoregames-3aa7e.appspot.com/o/HARDCORE%20GAMING%20Logotipo%20PNG.png?alt=media&token=c4799166-23c1-4fe8-8396-fa13767c035b" width="190" class="CToWUd" data-bit="iit"> </div></div><div style="padding:0 20px 20px 20px"><hr style="border-color:#e0e0e0;border-width:1px"><div style="padding:10px 0;text-align:justify;line-height:1.3"> <div style="font-size:19px;margin-bottom:30px">¡Hola!<br></div> <div id="body" style="margin-top: 8%;"> Hemos recibido tu compra, a continuación se detallan los datos de acceso necesarios para obtener tu producto: <hr style="border-color:#e0e0e0;border-width:1px"> </div> <div style="margin-top:40px"> Equipo Hardcore Games </div></div><hr style="border-color:#e0e0e0;border-width:1px"><div style="padding:12px;text-align:left"> <div style="font-size:13px"> <div style="font-size:15px;font-weight:bold;margin-bottom:5px">Contacta a soporte:</div> <a href="mailto:hardcorgamesx@gmail.com" style="text-decoration:none;color:black;display:flex;float:left" target="_blank"> <img style="width:20px" src="https://ci4.googleusercontent.com/proxy/bN9cvP1P6fpjNlf1RWVks6gbzAJFexZgOiQitHCz1R6iSMlLqFULZ5n--57oj39eObIWv_0cwM21CjhFt2IZqWbTwOdCquh6GcNOJ0nKQUo=s0-d-e1-ft#https://backend.plattaforma.com/images/iconos/email-black.png" class="CToWUd" data-bit="iit">&nbsp;hardcorgamesx@gmail.com </a> <a style="float:left;text-decoration:none;color:black">&nbsp;|&nbsp;</a> <a href="https://wa.link/y72sz9" style="text-decoration:none;color:black;display:flex" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://wa.me/50766094872&amp;source=gmail&amp;ust=1700761454173000&amp;usg=AOvVaw0vROaGkqYwpmeagr8k1FP4"> <img style="width:20px" src="https://ci6.googleusercontent.com/proxy/YIHg9Jq-iFEJYfxml9vCTYAnNKH9wWzmjPZSCGZE3MCovRXxisN_qwG5bfjssweETXYSOCxy2h79G_xXomw76yHkyAZQqnzkqu4zx3lo1KhrzvU=s0-d-e1-ft#https://backend.plattaforma.com/images/iconos/whatsapp-black.png" class="CToWUd" data-bit="iit"> +57&nbsp;3247259150 </a> <div style="font-size:15px;font-weight:bold;margin-bottom:5px"></div> <a href="https://whatsapp.com/channel/0029Va0NflMBKfi45Z51UP39" style="text-decoration:none;color:black;display:flex" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://wa.me/50766094872&amp;source=gmail&amp;ust=1700761454173000&amp;usg=AOvVaw0vROaGkqYwpmeagr8k1FP4"> <img style="width:20px" src="https://ci6.googleusercontent.com/proxy/YIHg9Jq-iFEJYfxml9vCTYAnNKH9wWzmjPZSCGZE3MCovRXxisN_qwG5bfjssweETXYSOCxy2h79G_xXomw76yHkyAZQqnzkqu4zx3lo1KhrzvU=s0-d-e1-ft#https://backend.plattaforma.com/images/iconos/whatsapp-black.png" class="CToWUd" data-bit="iit">Más promociones aquí</a><br> </div> <hr style="border-color:#e0e0e0;border-width:1px"> <div style="padding:12px;text-align:left"> <div style="font-size:13px"> <div style="font-size:15px;font-weight:bold;margin-bottom:20px">Como instalar:</div> <div style="font-size:13px;font-weight:bold;margin-bottom:15px">Consolas Xbox:</div> <div style="font-size:12px;font-weight:bold;margin-bottom:5px">Instalación licencia primaria:</div> <a href="https://youtu.be/B76Qu8vGBCQ" style="text-decoration:none;color:black;display:flex;color: dodgerblue;" target="_blank">Click aquí</a> <div style="font-size:12px;font-weight:bold;margin-top:15px">Instalación licencia secundaria:</div> <a href="https://youtu.be/-WxGkAG__pQ?si=x1-kAa-1ph1EqkL8" style="text-decoration:none;color:black;display:flex;color: dodgerblue;" target="_blank">Click aquí</a> <div style="font-size:12px;font-weight:bold;margin-top:15px">Instalación licencia PC</div> <a href="https://www.youtube.com/watch?v=Q2VhD64uSVU" style="text-decoration:none;color:black;display:flex;color: dodgerblue;" target="_blank">Click aquí</a> <div style="font-size:12px;font-weight:bold;margin-top:15px">¿Cómo instalar juegos en XBOX?</div> <a href="https://www.youtube.com/watch?v=4TDpSrJ0aqM" style="text-decoration:none;color:black;display:flex;color: dodgerblue;" target="_blank">Click aquí</a> <br><br> <div> Copyright 2025 </div> </div> <div class="yj6qo"></div> <div class="adL"></div> </div></div>'
EMAIL_FOR_SALE = os.getenv("EMAIL_FOR_SALE")
TOKEN_CONFIRM_SALE = 'XqYH26xdzLidEFa'

#Bold Produccion
API_KEY_BOLD = os.getenv("API_KEY_BOLD")
SECRET_KEY_BOLD = os.getenv("SECRET_KEY_BOLD")
